#!/bin/bash
#SBATCH -J MonteCarlo
#SBATCH -A cs475-575
#SBATCH -p class
#SBATCH --gres=gpu:1
#SBATCH -o montecarlo.out
#SBATCH -e montecarlo.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=lixiaoyi@oregonstate.edu
#./montecarlo
for i in 16384 32768 65536 131072 262144 524288 1048576
do
	for j in 16 32 64 128
	do
		/usr/local/apps/cuda/cuda-10.1/bin/nvcc -DNUMTRIALS=$i -DBLOCKSIZE=$j -o montecarlo montecarlo.cu
		./montecarlo
	done
done
